

all:
	# sqlite3 ex3.db < ../ex2/ex2.sql
	sqlite3 -echo ex3.db < ../ex2/ex2.sql
	sqlite3 -echo ex3.db < ex3.sql
	sqlite3 -echo ex3.db < ex4.sql
	sqlite3 -echo ex3.db < ex5.sql
	sqlite3 -echo ex3.db < ex6.sql
	sqlite3 -echo ex3.db < ex7.sql

clean:
	rm -rf ex3.db
